spring:
  datasource:
    url : jdbc:mysql://localhost:3306/DUBBIMAGE?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: dubbi
    password: kang8349
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      temp:
        use_jdbc_metadata_defaults : false
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

app:
  file-storage-location: 'uploads/'

server:
  port: 9003